#!/usr/bin/env python

# Converts binary files into C arrays
# usage: bin2c fileA varA [fileB varB] ...
import os
import sys
if len(sys.argv) < 3:
  print 'usage: bin2c fileA varA [fileB varB] ...'
  exit(1);
arg = iter(sys.argv[1:])
for f in arg:
    sz = os.path.getsize(f)
    if sz <= 0:
        arg.next()
        continue
    print 'static const unsigned char ' + arg.next() + '[' + str(sz) + '] = {\n' + \
        ''.join([('0x%02x, ' % ord(x)) for x in open(f,'rb').read()]) + '\n};'
